### ISSUE TITLE
question about compiler

### ISSUE THREAD

**Issue by wlnancy** [lingsamuel/YooScript#1]
Hello,I want to know how can I run the backend to change the output? Are there any requirements on the format of the input code?

**Comment by lingsamuel** [comment]
Hello.
I didn't expect someone can find this repo. This repo originally developed when I am a freshman in college. IIRC the main code comes from the dragonbook. This repo is... just for fun, not worth to learn and you can learn nothing from it. I recommend you to read some compiler books like the dragonbook if you want.

If you really want to try this repo, I add a test case and outputs in repo. I lost all ignored files of this repo so I can't post them for you. You can change the path in `src/Controller` and run it to transpile the `.yoo` file, and run `src/Backend/SysVim/VirtualMachine` to run the generated `.sysvim` file. I forget how to print in this toy language (or I didn't implement it maybe), so you have to read the `VMStack.txt` to see the execution path.

At last, this repo is just a backup, not worth to learn, please read textbook instead...

**Comment by wlnancy** [comment]
Hello,
Thanks for your suggestion, I want to implement a interpreter recently so I want to learn it through the example. I will learn from books and examples in the future. Anyway,thanks for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月19日(星期五) 下午3:27
收件人:&nbsp;"DragonInstitute/YooScript"<YooScript@noreply.github.com&gt;;
抄送:&nbsp;"王蕾"<945389942@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DragonInstitute/YooScript] question about compiler (#1)





 
Hello.
 I didn't expect someone can find this repo. This repo originally developed when I am a freshman in college. IIRC the main code comes from the dragonbook. This repo is... just for fun, not worth to learn and you can learn nothing from it. I recommend you to read some compiler books like the dragonbook if you want.
 
If you really want to try this repo, I add a test case and outputs in repo. I lost all ignored files of this repo so I can't post them for you. You can change the path in src/Controller and run it to transpile the .yoo file, and run src/Backend/SysVim/VirtualMachine to run the generated .sysvim file. I forget how to print in this toy language (or I didn't implement it maybe), so you have to read the VMStack.txt to see the execution path.
 
At last, this repo is just a backup, not worth to learn, please read textbook instead...
